### PR TITLE
Fix typo: Payer to Payee

### PR DESCRIPTION
**Pull request by oscarguindzberg**

### CODE REVIEW

**Comment by schildbach** [comment]
Merged, thanks.

**Comment by oscarguindzberg** [comment]
Am I missing something or the commit was not merged?

**Comment by schildbach** [comment]
I do not use GitHub's "Merge" button because it creates these ugly merge commits. Instead, I merge on the command line. GitHub sometimes does not understand this properly.

**Comment by oscarguindzberg** [comment]
ok, I see the merged commit now. thanks

**Pull request closed without merging**
