### PR TITLE
Create market-promo-text-fa.txt

### PR DESCRIPTION
**Pull request by abeikverdi**
Farsi/Persian localization

### CODE REVIEW

**Comment by schildbach** [comment]
Thanks for your contribution. All translations are managed on Transifex: https://www.transifex.com/bitcoin-wallet/bitcoin-wallet/
There is already a start of the Persian translation, maybe you'd like to help finishing it? If it gets closer to completion, I'll merge it into the app.

**Comment by abeikverdi** [comment]
Sounds good. Ill have a look and will help once I got some time.

**Comment by schildbach** [comment]
Since you translated a string that goes to the Play store page: a good start would be translating market-description.txt. It's currently entirely untranslated, but if it would be complete I'd put the translation up to Google Play.

**Comment by abeikverdi** [comment]
Yea sure.

**Comment by abeikverdi** [comment]
I completed the description translation. You can use that for Google Play description. cheers!

**Comment by spike31303130** [comment]
Lloyd's bank

**Comment by schildbach** [comment]
Thanks, I put the description up. I hope the formatting (RTL text) is right.

**Comment by abeikverdi** [comment]
Cool.. Yea Persian is RTL. It all looks good.

**Pull request closed without merging**
