### PR TITLE
Move to a native Material theme

### PR DESCRIPTION
**Pull request by langerhans**
This is simply a move to the native Theme.Material.*, basically the same as in #276 but without all the other changes. I thought having that out of the way is a good start to continue working with the newer widgets.

- Removes the gradient from the ActionBar as Material is all flat. The color is about the median between the previous gradient colors. But maybe you want to get a bit more colorful with this branch :) 
- Introduce Indigo 500 as accent color. Of course this is up to you which color you want to choose
- Don't let DialogBuilder override the Dialog style
- Hack to have white text in SearchView. This one seems a bit ugly, but works. I hope it can be removed with a move to Toolbar.

### CODE REVIEW

**Comment by schildbach** [comment]
Thanks, I merged this to `lollipop` and rebased on current master.

I tend to keep the testnet version less colorful and the mainnet version to use colors (mainly orange-brown), except for the signal colors green/red which are the same for both versions.

Yes, it would be great if we could make the searchview hack go away. Toolbar is luckily part of Lollipop (rather than only the design/appcompat libraries), so a switch should be possible.

**Comment by langerhans** [comment]
Thanks for the merge!

>I tend to keep the testnet version less colorful and the mainnet version to use colors (mainly orange-brown), except for the signal colors green/red which are the same for both versions.

I think so far you used to maintain the testnet version and then rebase the `prod` branch which would change the colors? Then you should change the accent color on this base branch and keep the colored one on the prod branch.  
Do you have experience how Eclipse can handle different source sets in the gradle build? If it can deal with it, then the test/prod changes can be largely simplified to a point where you just `./gradlew build` and you get both test and mainnet builds in the same process. That's what I do on my Doge branch now.

The switch to the Toolbar would probably be the next step now. I'll be around this week, but then go on winter vacation until the 31st, so there won't be any contributions from my side until then. I'll check back and see where you want to go then. I mean it's not a pressing issue, more keeping up to date with the platform :+1:

**Comment by schildbach** [comment]
I think everything from this PR is now on master. Thanks!

**Comment by langerhans** [comment]
Wow, sorry for letting this sit around for over a year 😨 
Anyway, I'm planning to update my fork soon. Maybe I can contribute a little more here too. I think there is still some stuff that could be useful. Maybe I'll catch you on IRC for a chat sometime. But thanks for the merge regardless 👍

**Pull request closed without merging**
