### PR TITLE
Such Toolbar. Very Tabs. Wow.

### PR DESCRIPTION
**Pull request by langerhans**
This is not ready for merging yet, I just wanted to have this here. Basically to start a discussion if it's even worth continuing this effort. This probably has some rough edges still, but you might want to check it out.

Modernizes a few things. Removes ActionBar and replaces it with Toolbar. This forces a move to the new styles from appcompat v7. Which in turn introduces Material Design.
I also implemented the new TabLayout for the settings, since the navigation with three list items always bugged me.

Let me know what you think, I'm also on IRC if you want a quicker way to discuss :)

### CODE REVIEW

**Comment by schildbach** [comment]
Thanks for this valuable contribution! Yeah, I agree we need to continue modernization of the GUI. I admit I refrained from this because I still use Eclipse and it cannot handle Android libraries (AARs) properly. I'm aware I need to switch, will try Android Studio 2.0 again soon if it works (previous versions did not).

I take it the new Toolbar doesn't work without also using the AppCompat theme, right? Because if it would, we could do that change separately.

Is the tabbed settings standard in any way? I've not seen this anywhere else so far. This doesn't mean I don't like it, just asking…

Another personal thing: I currently do not own any device with API level 23. Do your changes also work under API 21? I guess they should – if I'm right I'd prefer to stay at 21 for now.

**Comment by schildbach** [comment]
One thing I dislike about AppCompat is that it forces Material design on everyone, also on 4.x Android versions whose users are accustomed to Holo. Another disadvantage of this behaviour is it includes all the Material assets – increasing APK size by a whopping 1 MB.

**Comment by langerhans** [comment]
> I still use Eclipse    

Hm right, I didn't think much about eclipse when depending on support-v7. There is a plugin here, that could serve as (temporary) workaround for this: https://github.com/ksoichiro/gradle-eclipse-aar-plugin .
Some Google engineer recently said "We pretty much deprecated Eclipse", so I hope AS 2.0 works better for you.

> I take it the new Toolbar doesn't work without also using the AppCompat theme, right?  

Correct, you'll get an exception if your theme does not extend from Theme.AppCompat.*

> Is the tabbed settings standard in any way?  

The guidelines don't specifically mention tabs for settings, but they give some vague hints about where you can use tabs. One being to structure sibling views, which this PR pretty much does. I'm always a fan of reducing the navigation hierarchy. The settings guidelines even say you should only use sub-screens for 16 or more settings. One could argue that "About" is not settings at all and then you'd easily got under 16 which could be put into one view. Guess it's just a matter of taste.
On the other hand, this is a workaround for the fact that there is no PreferenceActivity with AppCompat support out of the box. You can make your own with AppCompatDelegate, but even then, with sub-screens you need some hacks to make it fully work.

> Do your changes also work under API 21?  

Yes. I tested them on API 19 and 23 yesterday. The change to compileSdkVersion merely means that you get the APIs to compile against. minSdk stays unchanged and would be as low as 7 for this change alone.

> on 4.x Android versions whose users are accustomed to Holo  

Users on 4.x are accustomed to a mix of Holo and Material since the launch of the Material AppCompat libs. There are apps that use it, there are apps that don't. From a work app I've seen complaints in the Play Store that we don't use enough Material. You won't ever be able to make everyone happy. You could technically supply Holo to old versions by using a values-v21 specifically for Material and overriding everything under it, but that would mean even more assets to ship and take care of.

>  increasing APK size by a whopping 1 MB  

True, that's not all too good. I'd argue that 1MB is not that much, looking at the average size of some apps, Bitcoin Wallet still seems pretty small. There is also `shrinkResources true` but that requires extensive testing so that not too much gets removed.

In the end it's your call if you want to move forward with this PR, or in which direction you'd like to push it :)

**Comment by schildbach** [comment]
Hm, my understanding is that Android 4+ devices already provide all Holo assets and Android 5+ devices provide all Material assets on top of that. So in theory it should be possible to create a style that uses Holo on Android 4 and Material on Android 5+, mostly without adding any assets to the app. Am I right?

But using such a configuration would not be compatible to the Widgets from AppCompat…

However we could fork off an Android 4 version of the app and continue developing for Android 5+, backporting important features to the Android 4 version. Although this means more work with multiple APKs, I tend to prefer such an approach. We could go full-force with Material features.

**Comment by langerhans** [comment]
Sadly, this is not how it works. Even on API < 21, if you don't extend your main theme from Theme.AppCompat.*, you'll get an exception. google pretty much wants to force everyone to use Material. AFAIK, you can't access the system Holo assets in such a way cause they are "private".   

Also, The Framework provided assets and classes seem to be less powerful as even on API 21+, most of the AppCompat widgets don't make any effort to switch to them.

The good thing is that Google Play by now supports such a config where you have two APKs for different versions. Gradle can automatically do such things but it's a bit messy to keep this in sync with such a big change. So a branch with the older version could work. Luckily, most of my changes don't touch any functional code so merging in important features might be easy enough. But overall the changes are not even that big, apart from some lines and colors. Maybe using the A/B testing feature of Google Play could help? Or even using the beta channel and getting some opinions?

**Comment by schildbach** [comment]
I played around with the various support libraries and Lollipop. I'm pretty sure I don't want AppCompat in the app, it's just too intrusive. Instead, I'd like to move minSdkVersion to API level 21 and publish two APKs. I started a ["lollipop" branch](https://github.com/schildbach/bitcoin-wallet/commits/lollipop) with some initial commits.

Unfortunately, there doesn't appear to exist a "design" library for minSdkVersion 21. I hope Google will fix that – there must be a market for apps that don't care about Android 4 and below… TabLayout should be pretty easy to port however.

These changes I could imagine for the Lollipop branch:
- Replace all icons with vector drawables.
- Use tinting and primary/secondary colors.
- Use the Camera2 API for the QR code scanner.
- Support the Marshmellow permission model.

**Comment by langerhans** [comment]
I could look into some of those. Maybe we should open an issue and close here to keep track of the proposed ideas for that branch?  

>Replace all icons with vector drawables.

Should be easy enough with the simple icons. I could re-trace them in SVG which can be converted into VD.
>Use tinting and primary/secondary colors.  

Pretty much my theme change from this PR. So this could be taken out and just remove the "AppCompat" part in it.
>Use the Camera2 API for the QR code scanner.

I saw you already asked ZXing about that and (surprisingly to me) were told that the project won't be developed much further? There is a scanner in the Google Play Service, but if you think AppCompat is intrusive, don't ever let GMS dependencies come near your build.gradle ;D
>Support the Marshmellow permission model.

Should be easy enough as the app doesn't require that many permissions you'd need to ask for. Pretty sure just camera and bluetooth.

**Pull request closed without merging**
